// Code generated by go generate; DO NOT EDIT.
// This file was generated at 05 Feb 20 19:45 AEDT,
// using data from https://github.com/SapphireServer/FFXIVOpcodes/raw/master/opcodes.json
package opcodes

var byCode = []map[uint32]string{
	100: "TellReq",
}

var byName = []map[string]uint32{
	"TellReq": 100,
}
