// Code generated by go generate; DO NOT EDIT.
// This file was generated at 05 Feb 20 19:45 AEDT,
// using data from https://github.com/SapphireServer/FFXIVOpcodes/raw/master/opcodes.json
package opcodes

var byCode = []map[uint32]string{
	3:  "ReqCharList",
	4:  "ReqEnterWorld",
	5:  "ClientVersionInfo",
	10: "ReqCharDelete",
	11: "ReqCharCreate",
}

var byName = []map[string]uint32{
	"ReqCharList":       3,
	"ReqEnterWorld":     4,
	"ClientVersionInfo": 5,
	"ReqCharDelete":     10,
	"ReqCharCreate":     11,
}
