// Code generated by go generate; DO NOT EDIT.
// This file was generated at 05 Feb 20 19:45 AEDT,
// using data from https://github.com/SapphireServer/FFXIVOpcodes/raw/master/opcodes.json
package opcodes

var byCode = []map[uint32]string{
	2:  "LobbyError",
	12: "LobbyServiceAccountList",
	13: "LobbyCharList",
	14: "LobbyCharCreate",
	15: "LobbyEnterWorld",
	21: "LobbyServerList",
	23: "LobbyRetainerList",
}

var byName = []map[string]uint32{
	"LobbyError":              2,
	"LobbyServiceAccountList": 12,
	"LobbyCharList":           13,
	"LobbyCharCreate":         14,
	"LobbyEnterWorld":         15,
	"LobbyServerList":         21,
	"LobbyRetainerList":       23,
}
